### ISSUE TITLE
set_checksum() without cloning

### ISSUE THREAD

**Issue by TjeuKayim** [nickhs/scuttle6#1]
https://github.com/nickhs/scuttle6/blob/eeda563b98401d7f546c9b67f20a87b819f85dd9/src/main.rs#L130-L132

This is the code I ended up with:

```rust
    icmp.set_payload(&payload);
    let checksum = checksum(&icmp.to_immutable(), &prev_packet.get_source(), &prev_packet.get_destination());
    icmp.set_checksum(checksum);
```

`to_immutable()` borrows `icmp`, works fine in my app.

Thanks for the inspiration!

**Comment by nickhs** [comment]
Thanks for sending this in! That is indeed a lot cleaner, as you can see the borrow checker and I weren't getting on :smile:.

**Comment by TjeuKayim** [comment]
My app is using ip6tables NFQUEUE instead of `libpcap` to intercept and send packets. It is responding with spoofed Time Exceeded to all protocols (so not limited to ICMP traceroute) and packets with higher hop-limit are routed normally. I want to open source it soon.

So another optimization I did was to use the prevous MAC destination as source in the response and vice versa. Calling the ARP command is unnecessary.
